import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google"
import "./globals.css";

const notoSansJP = Noto_Sans_JP({
  weight: "400",
  subsets: ["latin-ext"],
})

export const metadata: Metadata = {
  title: "tuna2134 website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body style={notoSansJP.style}>
        {children}
      </body>
    </html>
  );
}
